window.GameEngine.registerGame('mathSprint', {
    isP1: false,
    
    getInitialState: function() {
        return {
            p1Score: 0,
            p2Score: 0,
            status: 'waiting',
            winner: null,
            currentQuestion: this.generateQuestion()
        };
    },

    generateQuestion: function() {
        const ops = ['+', '-', '*'];
        const op = ops[Math.floor(Math.random() * ops.length)];
        let a, b;
        if (op === '*') {
            a = Math.floor(Math.random() * 10) + 1;
            b = Math.floor(Math.random() * 10) + 1;
        } else {
            a = Math.floor(Math.random() * 50) + 10;
            b = Math.floor(Math.random() * 50) + 10;
            if (op === '-' && a < b) { const temp = a; a = b; b = temp; }
        }
        
        const ans = op === '+' ? a+b : (op === '-' ? a-b : a*b);
        // Generate options
        let options = [ans, ans + Math.floor(Math.random()*5+1), ans - Math.floor(Math.random()*5+1)];
        options.sort(() => Math.random() - 0.5);

        return { q: \`\${a} \${op} \${b} = ?\`, ans: ans, opts: options };
    },

    getHTML: function() {
        return \`
        <div class="w-full flex flex-col items-center max-w-[320px] mx-auto pt-4">
            <div class="clay-panel px-4 py-1 rounded-full border-blue-500 mb-4 shrink-0">
                <h3 class="text-xs font-mono tracking-widest text-blue-500 uppercase">Math Sprint</h3>
            </div>
            
            <p id="ms-status" class="mb-2 font-mono text-xs uppercase tracking-widest text-center px-4 py-1 rounded-xl bg-white/5 border border-gray-200">Menunggu...</p>
            
            <div class="flex justify-between w-full mb-4 px-2">
                <div class="text-xs font-mono font-bold text-clay-tertiary">P1: <span id="ms-p1">0</span></div>
                <div class="text-xs font-mono font-bold text-clay-accent">P2: <span id="ms-p2">0</span></div>
            </div>

            <div class="clay-card w-full p-8 rounded-3xl flex items-center justify-center mb-6 border-2 border-clay-secondary">
                <span id="ms-q" class="font-heading font-black text-3xl text-clay-text">?</span>
            </div>

            <div class="grid grid-cols-3 gap-3 w-full" id="ms-opts">
                <!-- Generated by JS -->
            </div>
        </div>
        \`;
    },

    init: function() {
        // Nothing special to init locally
    },

    updateUI: function(state, isP1) {
        this.isP1 = isP1;
        const statusEl = document.getElementById('ms-status');
        const p1El = document.getElementById('ms-p1');
        const p2El = document.getElementById('ms-p2');
        const qEl = document.getElementById('ms-q');
        const optsContainer = document.getElementById('ms-opts');

        if (!statusEl) return;

        p1El.innerText = state.p1Score;
        p2El.innerText = state.p2Score;

        if (state.status === 'waiting') {
            statusEl.innerText = "Bersiap...";
            qEl.innerText = "Siap?";
            optsContainer.innerHTML = "";
            if (window.isHost) {
                setTimeout(() => {
                    if(window.syncRoomState) window.syncRoomState({ 'gameState.status': 'playing' });
                }, 3000);
            }
        } 
        else if (state.status === 'playing') {
            statusEl.innerText = "JAWAB CEPAT!";
            qEl.innerText = state.currentQuestion.q;
            
            // Avoid re-rendering if options are the same to not break clicking
            if (optsContainer.dataset.ans !== state.currentQuestion.ans.toString()) {
                optsContainer.dataset.ans = state.currentQuestion.ans;
                optsContainer.innerHTML = state.currentQuestion.opts.map(opt => 
                    \`<button onclick="window.GameEngine.games.mathSprint.answer(\${opt})" class="clay-panel border-blue-500 text-clay-text py-4 rounded-xl font-heading font-bold text-xl active:scale-95 transition hover:bg-blue-500/20">\${opt}</button>\`
                ).join('');
            }
        }
        else if (state.status === 'finished') {
            statusEl.innerText = state.winner === 'p1' ? "PLAYER 1 MENANG!" : (state.winner === 'p2' ? "PLAYER 2 MENANG!" : "SERI!");
            qEl.innerText = "Selesai!";
            optsContainer.innerHTML = "";
        }
    },

    answer: function(ans) {
        if (!window.roomData || window.roomData.gameState.status !== 'playing') return;
        const state = window.roomData.gameState;
        
        if (ans === state.currentQuestion.ans) {
            window.AudioEngine.playClick();
            // Correct
            const key = this.isP1 ? 'gameState.p1Score' : 'gameState.p2Score';
            const newScore = (this.isP1 ? state.p1Score : state.p2Score) + 1;
            
            if (window.syncRoomState) {
                let updates = {};
                updates[key] = newScore;
                
                // If reached 10, win
                if (newScore >= 10) {
                    updates['gameState.status'] = 'finished';
                    updates['gameState.winner'] = this.isP1 ? 'p1' : 'p2';
                    const mainP1 = window.roomData.p1.score + (this.isP1 ? 1 : 0);
                    const mainP2 = window.roomData.p2.score + (!this.isP1 ? 1 : 0);
                    updates['p1.score'] = mainP1;
                    updates['p2.score'] = mainP2;
                } else if (window.isHost || !window.isHost) {
                    // Generate next question
                    // Both can generate but host's will overwrite. For simplicity, whoever answers correctly generates the next question
                    updates['gameState.currentQuestion'] = this.generateQuestion();
                }
                
                window.syncRoomState(updates);
            }
        } else {
            // Wrong answer penalty (optional, maybe just buzz sound)
        }
    }
});
